### ISSUE TITLE
Unexpected stop on logging into twitter for the first time

### ISSUE THREAD

**Issue by akoul** [privly/privly-android#45]
Bug Report : 

* Application crashes when you login to the twitter account for the first time and scroll through the tweets. 
* Logcat Output : 

03-06 11:40:21.896  10910-10910/ly.priv.mobile E/InputEventReceiver﹕ Exception dispatching input event.
03-06 11:40:21.896  10910-10910/ly.priv.mobile D/AndroidRuntime﹕ Shutting down VM
03-06 11:40:21.945  10910-10910/ly.priv.mobile E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ly.priv.mobile, PID: 10910
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427422, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]

**Comment by vshivam** [comment]
@akoul Formatted the bug report.

**Comment by akoul** [comment]
@vshivam THANKS
 Also, the app seems to crash everytime you scroll through the tweets.

**Comment by vshivam** [comment]
If you could fix the bug and make a pull request to the develop branch, I could take a look.

**Comment by vshivam** [comment]
I have not been able to reproduce this. Are you using the latest code from master / develop ?

**Comment by akoul** [comment]
@vshivam Sorry for the late reply. I noticed that this error occurs after installing the app and using it for the first few times. Why don't you reinstall the app(gradle-develop) or try clearing data/cache from the app setting and then try it. Scrolling through the tweets up/down causes the app to force shut.
I'm attaching the screenshot of the force close:

![screenshot_2015-03-06-23-14-30](https://cloud.githubusercontent.com/assets/5782689/6539863/e300f858-c4a7-11e4-93b3-0ea606e18aa6.png)

**Comment by akoul** [comment]
I am using the latest code from develop branch of privly git.
I'll try to fix the error and make a pull request.

**Comment by akoul** [comment]
I am posting a .gif file of my screen recording. 
![screenrecord 1](https://cloud.githubusercontent.com/assets/5782689/6540196/595dda6c-c4b6-11e4-8d30-e7de28b0599d.gif)

**Comment by vshivam** [comment]
Steps to Reproduce : 

* Scroll down to the last tweet when more tweets start to load. 
* Scroll up while the tweets are loading. 
* App crashes.

**Comment by vshivam** [comment]
@akoul Just pushed a commit to the develop branch. Looks like this issue has been fixed. Can you check and confirm ?

**Comment by akoul** [comment]
I'll do that in some time and let you know

**Comment by akoul** [comment]
I'm still getting the same app-force close on scrolling through the tweets.

**Comment by vshivam** [comment]
Do you have this line :
mListViewPosts.addFooterView(mFooterView);

In the initializeComponent(View v) method of the MicroblogListPosts.java
class ?

**Comment by vshivam** [comment]
Sorry, MicroblogListPostsFragment.java class.

**Comment by akoul** [comment]
Yes, I do. I cloned the repository all over again with the latest commit and then compiled the files.

**Comment by akoul** [comment]
I wanted to ask as to whether you have used Twitter SDK or Intent Share for integration of Twitter into Privly? Also, can we used the ASNE library to integrate social platforms ?
The link is https://github.com/gorbin/ASNE. I haven't tried it though.

**Comment by vshivam** [comment]
If you check out the develop branch of the repo. It does not have that
line. That's the line which is causing the issue most probably.

Here's the link to the latest code :
https://github.com/privly/privly-android/blob/develop/src/main/java/ly/priv/mobile/api/gui/microblogs/MicroblogListPostsFragment.java

**Comment by akoul** [comment]
Commenting out that line made the difference. Now the bug seems to have been resolved.

**Comment by vshivam** [comment]
Bug Fixed. 

Commit : https://github.com/privly/privly-android/commit/d45803a62d3fc88bf950a9425e425a39f5507e2d
